# Generated by Django 6.0.7 on 2026-08-02 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driver_name', models.CharField(blank=True, max_length=150)),
                ('morning_scheduled_time', models.CharField(blank=True, max_length=20)),
                ('morning_arrival_time', models.CharField(blank=True, max_length=20)),
                ('morning_passengers', models.CharField(blank=True, max_length=300)),
                ('evening_scheduled_time', models.CharField(blank=True, max_length=20)),
                ('evening_arrival_time', models.CharField(blank=True, max_length=20)),
                ('evening_passengers', models.CharField(blank=True, max_length=300)),
                ('recorded_by_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.driver')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('morning', 'صبح'), ('evening', 'عصر')], default='morning', max_length=10)),
                ('reason', models.CharField(max_length=300)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='core.driverreport')),
            ],
        ),
        migrations.CreateModel(
            name='DriverTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=20)),
                ('destination', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.driverreport')),
            ],
        ),
    ]
