# Generated by Django 6.0.7 on 2026-08-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_driver_driverreport_driverdelay_drivertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverreport',
            name='odometer_end',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='driverreport',
            name='odometer_start',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
