# Generated by Django 6.0.7 on 2026-08-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_driverreport_odometer_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'مدیر'), ('data_entry', 'کاربر ثبت'), ('viewer', 'ناظر'), ('driver', 'راننده')], default='viewer', max_length=20),
        ),
    ]
