# Generated by Django 6.0.7 on 2026-08-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportitem',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
