# Generated by Django 6.0.7 on 2026-08-04 10:07

import django.db.models.deletion
from django.db import migrations, models


def carry_over_item_area(apps, schema_editor):
    """متراژی که قبلاً روی آیتم‌های کاری ثبت شده بود را به ReportProgress منتقل می‌کند.

    چون متراژ به‌ازای هر نفر ثبت می‌شد، برای هر (گزارش، پروژه، فعالیت) فقط یک ردیف
    با بیشترین مقدار ساخته می‌شود تا کار مشترکِ چند نفر چندبار شمرده نشود.
    """
    ReportItem = apps.get_model('core', 'ReportItem')
    ReportProgress = apps.get_model('core', 'ReportProgress')

    buckets = {}
    for item in ReportItem.objects.exclude(area=0):
        key = (item.report_id, item.project_id, item.activity)
        prev = buckets.get(key)
        if prev is None or item.area > prev.area:
            buckets[key] = item

    for item in buckets.values():
        ReportProgress.objects.create(
            report_id=item.report_id,
            project_id=item.project_id,
            project_name=item.project_name,
            stage=item.activity,
            area=item.area,
            desc='منتقل‌شده از متراژ آیتم کاری',
        )


def undo_carry_over(apps, schema_editor):
    ReportProgress = apps.get_model('core', 'ReportProgress')
    ReportProgress.objects.filter(desc='منتقل‌شده از متراژ آیتم کاری').delete()


def approve_existing_usages(apps, schema_editor):
    """مصرف موادی که پیش از افزوده‌شدن گردش تأیید ثبت شده، تأییدشده حساب می‌شود."""
    MaterialUsage = apps.get_model('core', 'MaterialUsage')
    MaterialUsage.objects.update(status='approved')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_projectstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('stage', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.dailyreport')),
            ],
        ),
        # ابتدا متراژ موجود منتقل شود، بعد ستون قدیمی حذف گردد.
        migrations.RunPython(carry_over_item_area, undo_carry_over),
        migrations.RemoveField(
            model_name='reportitem',
            name='area',
        ),
        migrations.AddField(
            model_name='materialusage',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش‌نویس'), ('waiting', 'در انتظار تأیید'), ('approved', 'تأیید شد'), ('revision', 'نیاز به اصلاح')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='materialusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # رکوردهای قبلی که بدون گردش تأیید ثبت شده‌اند تأییدشده علامت می‌خورند.
        migrations.RunPython(approve_existing_usages, noop),
    ]
