# Generated by Django 6.0.7 on 2026-08-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_report_progress_and_usage_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='resubmitted',
            field=models.BooleanField(default=False),
        ),
    ]
