# Generated by Django 6.0.7 on 2026-08-04 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def group_material_usage_into_reports(apps, schema_editor):
    """مصرف‌های موادِ مستقل قدیمی را به‌ازای هر روز/کاربر یک گزارش واحد می‌کند."""
    MaterialUsage = apps.get_model('core', 'MaterialUsage')
    MaterialUsageReport = apps.get_model('core', 'MaterialUsageReport')
    reports_by_key = {}
    for usage in MaterialUsage.objects.all().order_by('created_at'):
        key = (usage.date, usage.recorded_by_id)
        report = reports_by_key.get(key)
        if report is None:
            report = MaterialUsageReport.objects.create(
                date=usage.date,
                recorded_by_id=usage.recorded_by_id,
                recorded_by_name=usage.recorded_by_name,
                status='approved',
            )
            reports_by_key[key] = report
        usage.report_id = report.id
        usage.save(update_fields=['report'])


def approve_existing_driver_reports(apps, schema_editor):
    """سابقهٔ گزارش‌های راننده که پیش از این قابلیت ثبت شده، تأییدشده حساب می‌شود."""
    DriverReport = apps.get_model('core', 'DriverReport')
    DriverReport.objects.update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dailyreport_resubmitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialUsageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recorded_by_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('draft', 'پیش‌نویس'), ('waiting', 'در انتظار تأیید'), ('approved', 'تأیید شد'), ('revision', 'نیاز به اصلاح')], default='draft', max_length=20)),
                ('resubmitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_usage_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUsageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.materialusagereport')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='DriverFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.driverreport')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.AddField(
            model_name='driverreport',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش‌نویس'), ('waiting', 'در انتظار تأیید'), ('approved', 'تأیید شد'), ('revision', 'نیاز به اصلاح')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='driverreport',
            name='resubmitted',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(approve_existing_driver_reports, migrations.RunPython.noop),
        migrations.AddField(
            model_name='materialusage',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.materialusagereport'),
        ),
        migrations.RunPython(group_material_usage_into_reports, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='materialusage',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.materialusagereport'),
        ),
        migrations.RemoveField(
            model_name='materialusage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='materialusage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='materialusage',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='materialusage',
            name='recorded_by_name',
        ),
        migrations.RemoveField(
            model_name='materialusage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='materialusage',
            name='updated_at',
        ),
        migrations.AlterModelOptions(
            name='materialusage',
            options={},
        ),
    ]
