# Generated by Django 6.0.7 on 2026-08-05 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_materialusage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_hours', models.DecimalField(decimal_places=2, default=7.33, max_digits=5)),
                ('ot_mult', models.DecimalField(decimal_places=2, default=1.4, max_digits=5)),
                ('ins_rate', models.DecimalField(decimal_places=2, default=7, max_digits=5)),
                ('tax_exempt', models.DecimalField(decimal_places=2, default=400000000, max_digits=16)),
                ('components', models.JSONField(default=list)),
                ('brackets', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Payroll settings',
            },
        ),
        migrations.CreateModel(
            name='PayrollStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dept', models.CharField(blank=True, max_length=100)),
                ('married', models.BooleanField(default=False)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(blank=True, max_length=150)),
                ('dept', models.CharField(blank=True, max_length=100)),
                ('married', models.BooleanField(default=False)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('absent_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('worked_days', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('short_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('kpi', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('seniority', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('transport', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('responsibility', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('insurance_manual', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('reserve', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('loan', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.payrollmonth')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payrollstaff')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('month', 'staff')},
            },
        ),
    ]
