# Generated by Django 6.0.7 on 2026-08-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_payrollmonth_payrollsettings_payrollstaff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payrollstaff',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
