# Generated by Django 6.0.7 on 2026-08-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_payrollentry_position_payrollstaff_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'مدیر'), ('data_entry', 'کاربر ثبت'), ('viewer', 'ناظر'), ('driver', 'راننده'), ('accountant', 'حسابداری')], default='viewer', max_length=20),
        ),
    ]
