# Generated by Django 6.0.7 on 2026-09-07 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=80)),
                ('name', models.CharField(max_length=300)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=100)),
                ('category', models.CharField(blank=True, db_index=True, max_length=150)),
                ('sepidar_item_id', models.CharField(blank=True, max_length=60)),
                ('sellable', models.BooleanField(default=True)),
                ('batch_tracked', models.BooleanField(default=False)),
                ('hazardous', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('lead_time_days', models.PositiveSmallIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('supplies_workshop', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_package_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('pack_size', models.CharField(blank=True, max_length=60)),
                ('grit', models.CharField(blank=True, max_length=40)),
                ('shade', models.CharField(blank=True, max_length=80)),
                ('barcode', models.CharField(blank=True, max_length=60)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='core.product')),
            ],
            options={
                'ordering': ['product__brand', 'product__name', 'pack_size'],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=80)),
                ('produced_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.sku')),
            ],
            options={
                'ordering': ['expires_on', 'batch_no'],
                'unique_together': {('sku', 'batch_no')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier'),
        ),
        migrations.CreateModel(
            name='PackConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField()),
                ('box_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpacks_to', to='core.sku')),
                ('unit_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs_from', to='core.sku')),
            ],
            options={
                'unique_together': {('box_sku', 'unit_sku')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'ورود کالا'), ('sale', 'فروش'), ('return', 'مرجوعی'), ('workshop', 'مصرف کارگاه'), ('transfer_out', 'انتقال — خروج'), ('transfer_in', 'انتقال — ورود'), ('unpack_out', 'شکستن بسته — خروج'), ('unpack_in', 'شکستن بسته — ورود'), ('count', 'اصلاح انبارگردانی')], max_length=20)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('date', models.DateField()),
                ('ref', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.stockbatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.warehouse')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['sku', 'warehouse'], name='core_stockm_sku_id_39643d_idx'), models.Index(fields=['date'], name='core_stockm_date_0e5254_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_code', models.CharField(blank=True, max_length=60)),
                ('min_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reserved_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('counted_at', models.DateField(blank=True, null=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='core.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='core.warehouse')),
            ],
            options={
                'unique_together': {('sku', 'warehouse')},
            },
        ),
    ]
