# Generated by Django 6.0.7 on 2026-09-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_supplier_warehouse_sku_stockbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='sepidar_item_id',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
