# Generated by Django 6.0.7 on 2026-09-07 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sku_sepidar_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('movement_kind', models.CharField(choices=[('receipt', 'ورود کالا'), ('sale', 'فروش'), ('return', 'مرجوعی'), ('workshop', 'مصرف کارگاه'), ('transfer_out', 'انتقال — خروج'), ('transfer_in', 'انتقال — ورود'), ('unpack_out', 'شکستن بسته — خروج'), ('unpack_in', 'شکستن بسته — ورود'), ('count', 'اصلاح انبارگردانی')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('posted', 'ثبت نهایی')], default='draft', max_length=20)),
                ('date', models.DateField()),
                ('counterparty', models.CharField(blank=True, max_length=200)),
                ('ref', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_vouchers', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='core.warehouse')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.stockvoucher'),
        ),
        migrations.CreateModel(
            name='StockVoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('batch_no', models.CharField(blank=True, max_length=80)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='core.sku')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.stockvoucher')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
