# Generated by Django 6.0.7 on 2026-09-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_stockvoucher_stockmovement_voucher_stockvoucherline'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='alt_to_base',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='alt_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sku',
            name='base_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='entered_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='entered_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='stockvoucherline',
            name='unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockvoucherline',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=14),
        ),
    ]
