# Generated by Django 6.0.7 on 2026-09-07 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sku_alt_to_base_sku_alt_unit_sku_base_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockvoucher',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_vouchers', to='core.warehouse'),
        ),
    ]
