# Generated by Django 6.0.7 on 2026-09-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_stockvoucher_to_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
