# Generated by Django 6.0.7 on 2026-09-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sku_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
