# Generated by Django 6.0.7 on 2026-09-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_warehouse_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='warehouse_code',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
