# Generated by Django 6.0.7 on 2026-09-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sku_warehouse_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='asset_code',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sku',
            name='handed_over_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='holder_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
