# Generated by Django 6.0.7 on 2026-09-15 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_action_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='asset_model',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sku',
            name='asset_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sku',
            name='asset_serial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sku',
            name='asset_status',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sku',
            name='asset_supplier',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sku',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sku',
            name='salvage_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sku',
            name='service_interval_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='useful_life_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='warranty_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssetInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('open', 'در جریان'), ('closed', 'بسته شده')], default='open', max_length=10)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by_name', models.CharField(blank=True, max_length=150)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_inspections', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='core.location')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'ثبت اموال'), ('handover', 'تحویل'), ('move', 'جابه\u200cجایی'), ('status', 'تغییر وضعیت'), ('repair', 'تعمیر'), ('service', 'سرویس و نگهداری'), ('inspection', 'بازرسی'), ('note', 'یادداشت')], max_length=20)),
                ('date', models.DateField()),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_events', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_events', to='core.sku')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.assetinspection')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetInspectionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(blank=True, max_length=150)),
                ('location_name', models.CharField(blank=True, max_length=100)),
                ('present', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ok', 'سالم'), ('needs_repair', 'نیاز به تعمیر'), ('in_repair', 'در تعمیر'), ('out_of_service', 'خارج از سرویس')], default='ok', max_length=20)),
                ('needs_action', models.BooleanField(default=False)),
                ('action', models.CharField(blank=True, choices=[('', '—'), ('expert', 'بررسی بیشتر توسط کارشناس'), ('service', 'سرویس'), ('repair', 'تعمیر'), ('replace', 'تعویض'), ('out_of_service', 'خروج از سرویس')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.assetinspection')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_lines', to='core.sku')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('inspection', 'sku'), name='inspection_line_unique')],
            },
        ),
    ]
