# Generated by Django 6.0.7 on 2026-09-15 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_asset_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('service_overdue', 'سرویس عقب\u200cافتاده'), ('service_soon', 'سرویس نزدیک'), ('needs_repair', 'نیاز به تعمیر'), ('in_repair', 'در تعمیر'), ('warranty_soon', 'گارانتی رو به پایان'), ('inspection', 'اقدام بازرسی'), ('missing', 'پیدا نشد در بازرسی')], max_length=20)),
                ('level', models.CharField(choices=[('high', 'فوری'), ('medium', 'مهم'), ('low', 'یادآوری')], default='medium', max_length=10)),
                ('key', models.CharField(db_index=True, max_length=80)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'باز'), ('done', 'انجام شد')], db_index=True, default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by_name', models.CharField(blank=True, max_length=150)),
                ('close_note', models.CharField(blank=True, max_length=500)),
                ('auto_closed', models.BooleanField(default=False)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_alerts', to='core.assetinspection')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_alerts', to='core.sku')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('key',), name='maintenance_alert_open_key')],
            },
        ),
    ]
