# Generated by Django 6.0.7 on 2026-09-16 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_maintenance_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('receipt', 'ورود کالا'), ('sale', 'فروش'), ('return', 'مرجوعی'), ('workshop', 'مصرف کارگاه'), ('transfer_out', 'انتقال — خروج'), ('transfer_in', 'انتقال — ورود'), ('unpack_out', 'شکستن بسته — خروج'), ('unpack_in', 'شکستن بسته — ورود'), ('count', 'اصلاح انبارگردانی'), ('issue_person', 'تحویل به شخص'), ('return_person', 'برگشت از شخص')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockvoucher',
            name='movement_kind',
            field=models.CharField(choices=[('receipt', 'ورود کالا'), ('sale', 'فروش'), ('return', 'مرجوعی'), ('workshop', 'مصرف کارگاه'), ('transfer_out', 'انتقال — خروج'), ('transfer_in', 'انتقال — ورود'), ('unpack_out', 'شکستن بسته — خروج'), ('unpack_in', 'شکستن بسته — ورود'), ('count', 'اصلاح انبارگردانی'), ('issue_person', 'تحویل به شخص'), ('return_person', 'برگشت از شخص')], max_length=20),
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'در حال شمارش'), ('posted', 'ثبت نهایی')], db_index=True, default='draft', max_length=10)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by_name', models.CharField(blank=True, max_length=150)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='core.warehouse')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('posted_diff', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.stockcount')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_lines', to='core.sku')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('count', 'sku'), name='stock_count_line_unique')],
            },
        ),
    ]
