# Generated by Django 6.0.7 on 2026-09-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_stock_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.TextField(blank=True),
        ),
    ]
