# Generated by Django 6.0.7 on 2026-09-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_production_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation', to='core.project'),
        ),
    ]
