# Generated by Django 6.0.7 on 2026-09-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_project_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='close_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='closed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='closed_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='closed_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
