# Generated by Django 6.0.7 on 2026-09-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_project_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('completed', 'کار تکمیل شد'), ('short', 'با کسری بسته شد'), ('incomplete_data', 'دادهٔ ناقص — بسته شد')], max_length=20),
        ),
    ]
