# Generated by Django 6.0.7 on 2026-09-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_close_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='general',
            field=models.BooleanField(default=False),
        ),
    ]
