# Generated by Django 6.0.7 on 2026-09-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_general_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='base_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='workstage',
            name='default_coefficient',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
