# Generated by Django 6.0.7 on 2026-09-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_stage_coefficients'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstage',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
