# Generated by Django 6.0.7 on 2026-09-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_final_stage_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
