# Generated by Django 6.0.7 on 2026-09-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_cost_per_hour', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('material_cost_per_m2', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('margin_percent', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='workstage',
            name='importance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='workstage',
            name='time_weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
    ]
