# Generated by Django 6.0.7 on 2026-09-27 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='drivertask',
            name='collected_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='drivertask',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='drivertask',
            name='route_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='drivertask',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.driverroute'),
        ),
        migrations.CreateModel(
            name='DriverMonthRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('rate_per_km', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=150)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_rates', to='core.driver')),
            ],
            options={
                'ordering': ['-month', 'driver__name'],
                'unique_together': {('driver', 'month')},
            },
        ),
    ]
