# Generated by Django 6.0.7 on 2026-09-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_pricing_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hourly_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
    ]
