# Generated by Django 6.0.7 on 2026-09-28 15:56

from django.db import migrations, models

# همان DASHBOARD_WIDGETS در core/access.py، اینجا ثابت تا مهاجرت با تغییرهای بعدی عوض نشود.
WIDGETS = [
    "dashboard.w.summary", "dashboard.w.trend", "dashboard.w.status", "dashboard.w.queue",
    "dashboard.w.day", "dashboard.w.projhours", "dashboard.w.staffhours", "dashboard.w.projects",
    "dashboard.w.pulse", "dashboard.w.material", "dashboard.w.expiry", "dashboard.w.stock",
    "dashboard.w.finance", "dashboard.w.maint", "dashboard.w.driver",
]


def grant(apps, schema_editor):
    """هر کس داشبورد دارد، همهٔ ویجت‌ها را هم می‌گیرد — تا امروز همه را می‌دید."""
    User = apps.get_model("core", "User")
    for u in User.objects.all():
        access = list(u.access or [])
        if "dashboard" in access:
            u.access = access + [k for k in WIDGETS if k not in access]
            u.save(update_fields=["access"])


def revoke(apps, schema_editor):
    User = apps.get_model("core", "User")
    for u in User.objects.all():
        access = list(u.access or [])
        if any(k in access for k in WIDGETS):
            u.access = [k for k in access if k not in WIDGETS]
            u.save(update_fields=["access"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_workstage_daily_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(grant, revoke),
    ]
