# Generated by Django 6.0.7 on 2026-09-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_project_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcountline',
            name='counted_qty',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='stockcountline',
            name='posted_diff',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='stockcountline',
            name='system_qty',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='qty',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
    ]
