# Generated by Django 6.0.7 on 2026-10-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_project_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialusage',
            name='kind',
            field=models.CharField(choices=[('use', 'مصرف'), ('waste', 'ضایعات'), ('return', 'برگشتی به انبار')], default='use', max_length=10),
        ),
        migrations.AddField(
            model_name='materialusage',
            name='stage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reportitem',
            name='location',
            field=models.CharField(blank=True, choices=[('workshop', 'کارگاه'), ('onsite', 'محل پروژه')], max_length=10),
        ),
        migrations.AddField(
            model_name='reportitem',
            name='overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportitem',
            name='rework',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportitem',
            name='rework_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
