# Generated by Django 6.0.7 on 2026-10-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_report_cost_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='price_list_name',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
