# Generated by Django 6.0.7 on 2026-10-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_sku_price_list_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='kg_per_litre',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
