# Generated by Django 6.0.7 on 2026-10-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_sku_kg_per_litre'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='plan_priority',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
