# Generated by Django 6.0.7 on 2026-10-04 09:42

import django.db.models.deletion
from django.db import migrations, models


KEY = "production.plan"


def grant(apps, schema_editor):
    """برنامه‌ریزی کارِ مدیر تولید است: به مدیرهایی داده می‌شود که «تولید» را دارند؛ بقیه را مسئول کاربران تیک می‌زند."""
    User = apps.get_model("core", "User")
    for u in User.objects.filter(role="manager"):
        access = list(u.access or [])
        if "production" in access and KEY not in access:
            u.access = access + [KEY]
            u.save(update_fields=["access"])


def revoke(apps, schema_editor):
    User = apps.get_model("core", "User")
    for u in User.objects.all():
        access = list(u.access or [])
        if KEY in access:
            u.access = [k for k in access if k != KEY]
            u.save(update_fields=["access"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_project_plan_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('by_name', models.CharField(blank=True, max_length=150)),
                ('note', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=150)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['date_from', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanOvertime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('people', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('stages', models.JSONField(blank=True, default=list)),
                ('crew', models.PositiveSmallIntegerField(default=1)),
                ('people', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanBaselineLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('station_name', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('people', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_baseline', to='core.project')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline', to='core.station')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('daily_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('not_before', models.DateField(blank=True, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_tasks', to='core.project')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_tasks', to='core.station')),
            ],
            options={
                'unique_together': {('project', 'stage')},
            },
        ),
        migrations.RunPython(grant, revoke),
    ]
