# Generated by Django 6.0.7 on 2026-10-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_production_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantask',
            name='batch',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
