# Generated by Django 6.0.7 on 2026-10-04 11:24

from django.db import migrations, models


import datetime

# تعطیلات رسمی سال ۱۴۰۵ از تقویم time.ir (مهر ۱۴۰۵). تعطیلات مذهبی ممکن است یک روز پس‌وپیش اعلام شوند؛
# مسئول برنامه‌ریزی از صفحهٔ «تعطیلات» اصلاحشان می‌کند.
HOLIDAYS_1405 = [
    (1, 1, "عید نوروز و عید سعید فطر"), (1, 2, "عید نوروز و تعطیل عید فطر"), (1, 3, "عید نوروز"), (1, 4, "عید نوروز"),
    (1, 12, "روز جمهوری اسلامی"), (1, 13, "سیزده به در"), (1, 25, "شهادت امام جعفر صادق (ع)"),
    (3, 6, "عید سعید قربان"), (3, 14, "رحلت امام خمینی و عید غدیر خم"), (3, 15, "قیام ۱۵ خرداد"),
    (4, 3, "تاسوعای حسینی"), (4, 4, "عاشورای حسینی"),
    (5, 13, "اربعین حسینی"), (5, 21, "رحلت رسول اکرم و شهادت امام حسن مجتبی (ع)"), (5, 22, "شهادت امام رضا (ع)"),
    (5, 30, "شهادت امام حسن عسکری (ع)"), (6, 8, "میلاد رسول اکرم و امام جعفر صادق (ع)"),
    (8, 22, "شهادت حضرت فاطمه زهرا (س)"), (10, 2, "ولادت امام علی (ع)"), (10, 16, "مبعث رسول اکرم (ص)"),
    (11, 4, "نیمهٔ شعبان"), (11, 22, "پیروزی انقلاب اسلامی"), (12, 9, "شهادت حضرت علی (ع)"),
    (12, 19, "عید سعید فطر"), (12, 20, "تعطیل عید سعید فطر"), (12, 29, "روز ملی شدن صنعت نفت"),
]


def seed(apps, schema_editor):
    from core.jalali import jalali_to_gregorian
    Holiday = apps.get_model("core", "PlanHoliday")
    for jm, jd, title in HOLIDAYS_1405:
        Holiday.objects.get_or_create(date=datetime.date(*jalali_to_gregorian(1405, jm, jd)), defaults={"title": title})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_plan_task_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
