# Generated by Django 6.0.7 on 2026-10-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_plan_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantask',
            name='crew',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
