# Generated by Django 6.0.7 on 2026-10-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_plan_task_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstage',
            name='wait_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlanQueueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('station', models.CharField(max_length=100)),
                ('ready_area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('load', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
            ],
            options={
                'ordering': ['date', 'id'],
                'unique_together': {('date', 'station')},
            },
        ),
    ]
