# Generated by Django 5.2.17 on 2026-10-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_plan_drying_and_queues"),
    ]

    operations = [
        migrations.AddField(
            model_name="planleave",
            name="hours",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="planleave",
            name="kind",
            field=models.CharField(
                choices=[("leave", "مرخصی"), ("general", "کار عمومی کارگاه")],
                default="leave",
                max_length=10,
            ),
        ),
    ]
