# Generated by Django 5.2.17 on 2026-10-05 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_plan_leave_hours_and_general_work"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("client", "به خواست کارفرما"),
                            ("material", "نرسیدن متریال"),
                            ("design", "تغییر طرح یا نقشه"),
                            ("payment", "پرداخت نشدن"),
                            ("site", "آماده نبودن محل کار"),
                            ("other", "سایر"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("by_name", models.CharField(blank=True, max_length=150)),
                ("resumed_by_name", models.CharField(blank=True, max_length=150)),
                ("due_shift", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pauses",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-start", "-id"],
            },
        ),
    ]
