# Generated by Django 6.0.7 on 2026-10-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_project_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True),
        ),
    ]
