# Generated by Django 6.0.7 on 2026-10-05 13:47

import django.db.models.deletion
from django.db import migrations, models


# فروشنده‌هایی که روی فاکتورهای قبلی (اکسل) آمده‌اند، با همان مشخصات.
ADDRESS = "اصفهان، اتوبان خلیج فارس، سیتی سنتر، طبقه سوم، A3-27"
SELLERS = [
    {"name": "مرکز پوشش", "province": "اصفهان", "city": "اصفهان"},
    {"name": "شرکت دیواژ نقش ماندگار", "national_id": "14014585480", "reg_no": "80552", "province": "اصفهان", "city": "اصفهان",
     "address": ADDRESS, "postal_code": "8169414875", "phone": "03136550486",
     "bank_note": "مبلغ فاکتور را به حساب جاری شماره IR360560952504004976967001 به نام شرکت دیواژ نقش ماندگار نزد بانک سامان واریز فرمایید"},
    {"name": "معین حیدری", "national_id": "12701795430", "province": "اصفهان", "city": "اصفهان", "address": ADDRESS,
     "postal_code": "8169414875", "phone": "03136550486"},
    {"name": "گروه آوان", "province": "اصفهان", "city": "اصفهان"},
]


def seed(apps, schema_editor):
    Seller = apps.get_model("core", "InvoiceSeller")
    for n, row in enumerate(SELLERS):
        Seller.objects.get_or_create(name=row["name"], defaults={**{k: v for k, v in row.items() if k != "name"}, "order": n})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_employee_monthly_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=40)),
                ('reg_no', models.CharField(blank=True, max_length=40)),
                ('economic_code', models.CharField(blank=True, max_length=40)),
                ('province', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('bank_note', models.CharField(blank=True, max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('scope', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('number', models.CharField(blank=True, db_index=True, max_length=40)),
                ('date', models.DateField()),
                ('status', models.CharField(default='draft', max_length=20)),
                ('seller', models.JSONField(default=dict)),
                ('buyer', models.JSONField(default=dict)),
                ('lines', models.JSONField(default=list)),
                ('adjustments', models.JSONField(default=list)),
                ('notes', models.JSONField(default=list)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('show_receipts', models.BooleanField(default=False)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('vat', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.project')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
