# Generated by Django 6.0.7 on 2026-10-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_sales_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='work_kind',
            field=models.CharField(blank=True, choices=[('door', 'درب و چهارچوب'), ('cabinet', 'کابینت و کمد'), ('furniture', 'مبلمان'), ('vanity', 'روشویی'), ('stairs', 'پله و نرده'), ('surface', 'دیوارکوب، سقف و سطوح'), ('trim', 'قرنیز و ابزار'), ('glass_metal', 'شیشه و فلز'), ('mixed', 'ترکیبی یا سایر')], max_length=20),
        ),
    ]
