# Generated by Django 6.0.7 on 2026-10-05 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_project_work_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived', to='core.salesinvoice'),
        ),
    ]
