# Generated by Django 6.0.7 on 2026-10-06 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_invoice_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('by_name', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(max_length=30)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('undone_by_name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanStationOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_key', models.CharField(db_index=True, max_length=120)),
                ('station_name', models.CharField(blank=True, max_length=100)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['date_from', 'id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='plan_stages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='plan_color',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='workstage',
            name='changeover_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.CreateModel(
            name='PlanRework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('stages', models.JSONField(blank=True, default=list)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('by_name', models.CharField(blank=True, max_length=150)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_reworks', to='core.project')),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
    ]
