# Generated by Django 6.0.7 on 2026-10-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_planning_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstage',
            name='helpers_ok',
            field=models.BooleanField(default=False),
        ),
    ]
