# Generated by Django 6.0.7 on 2026-10-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_stage_helpers'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='plan_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planleave',
            name='kind',
            field=models.CharField(choices=[('leave', 'مرخصی'), ('general', 'کار عمومی کارگاه'), ('fill', 'کار عمومی در وقتِ بی\u200cکاری')], default='leave', max_length=10),
        ),
    ]
