# Generated by Django 6.0.7 on 2026-10-07 11:07

from django.db import migrations, models


def top_coat(apps, schema_editor):
    """رنگ رویه کارِ سرکارگر است (قاعدهٔ ثابتِ برنامه‌ریزی)."""
    apps.get_model("core", "WorkStage").objects.filter(name="رنگ رویه").update(foreman_first=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_general_skill_fill'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='plan_foreman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workstage',
            name='foreman_first',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(top_coat, migrations.RunPython.noop),
    ]
