# Generated by Django 6.0.7 on 2026-10-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_foreman'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='onsite_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='onsite_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='onsite_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='onsite_stages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='onsite_team',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
