# Generated by Django 6.0.7 on 2026-10-08 09:40

from django.db import migrations, models


def coats(apps, schema_editor):
    """استر و رنگ در نهایت دو نوبت (قاعدهٔ ثابتِ برنامه‌ریزی): هر مرحله‌ای که نامش استر، پرایمر یا رنگ دارد و «پرداخت» نیست."""
    WorkStage = apps.get_model("core", "WorkStage")
    for s in WorkStage.objects.all():
        if not s.name.startswith("پرداخت") and any(w in s.name for w in ("استر", "پرایمر", "رنگ")):
            WorkStage.objects.filter(pk=s.pk).update(few_rounds=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_onsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsettings',
            name='plan_eff_base',
            field=models.DecimalField(decimal_places=1, default=50, max_digits=5),
        ),
        migrations.AddField(
            model_name='productionsettings',
            name='plan_eff_target',
            field=models.DecimalField(decimal_places=1, default=50, max_digits=5),
        ),
        migrations.AddField(
            model_name='workstage',
            name='few_rounds',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(coats, migrations.RunPython.noop),
    ]
