# Generated by Django 6.0.7 on 2026-10-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_efficiency_rounds"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="plan_mode",
            field=models.CharField(blank=True, choices=[("force", "فورس (اول صف)"), ("outside", "خارج از برنامه")], default="", max_length=10),
        ),
    ]
