# Generated by Django 6.0.7 on 2026-10-09 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_plan_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(blank=True, max_length=150)),
                ('kind', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=16)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('center', models.CharField(blank=True, max_length=10)),
                ('project_name', models.CharField(blank=True, max_length=250)),
                ('paid_to', models.CharField(blank=True, max_length=200)),
                ('receipt', models.TextField(blank=True)),
                ('has_receipt', models.BooleanField(default=False)),
                ('status', models.CharField(default='waiting', max_length=10)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash', to='core.project')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
