# Generated by Django 6.0.7 on 2026-10-09 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

TAB = "accounting"


def define_existing(apps, schema_editor):
    """تا پیش از این، هر کس فقط خودِ سربرگِ «دستیار حسابداری» را داشت تنخواه‌دار بود. همان‌ها (و هر کس ردیفِ تنخواه
    دارد) تنخواه‌دارِ تعریف‌شده می‌شوند. کسی که سربرگ را برای بخشِ دیگری دارد (فاکتور، حقوق، …) خودکار تنخواه‌دار نمی‌شود."""
    User = apps.get_model("core", "User")
    PettyCash = apps.get_model("core", "PettyCash")
    Holder = apps.get_model("core", "PettyCashHolder")
    with_rows = set(PettyCash.objects.values_list("holder_id", flat=True))
    for u in User.objects.all():
        access = list(u.access or [])
        bare = u.is_active and TAB in access and not any(k.startswith(TAB + ".") for k in access)
        if u.pk in with_rows or bare:
            Holder.objects.get_or_create(user=u, defaults={"active": True})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_payroll_in_accounting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('account', models.CharField(blank=True, max_length=40)),
                ('bank', models.CharField(blank=True, max_length=60)),
                ('limit', models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('updated_by_name', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='petty_holder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(define_existing, migrations.RunPython.noop),
    ]
