# Generated by Django 6.0.7 on 2026-10-09 23:02
# مسیرهای ثابت و نرخِ هر کیلومتر برداشته شد (هر دو جدول روی سایت خالی بود)؛ «سرویسِ مشتری» نشانِ خودش را گرفت.

from django.db import migrations, models
from django.db.models import Q


def mark_customer_services(apps, schema_editor):
    """ردیفی که نامِ مشتری یا مبلغِ دریافتی دارد «سرویسِ مشتری» است."""
    DriverTask = apps.get_model("core", "DriverTask")
    DriverTask.objects.filter(~Q(customer_name="") | Q(collected_amount__gt=0)).update(customer_service=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_petty_cash_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivertask',
            name='route',
        ),
        migrations.RemoveField(
            model_name='drivertask',
            name='route_price',
        ),
        migrations.AddField(
            model_name='drivertask',
            name='customer_service',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_customer_services, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='DriverMonthRate',
        ),
        migrations.DeleteModel(
            name='DriverRoute',
        ),
    ]
