# Generated by Django 6.0.7 on 2026-10-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_driver_customer_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsettings',
            name='plan_reference_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
